# name: Deploy to Azure
#
# on:
#   push:
#     branches:
#       - main
#
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#
#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3
#
#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: "3.9"
#
#     - name: Install Dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r AzureResumeFunction/requirements.txt
#
#     - name: Deploy ARM Template
#       uses: azure/arm-deploy@v1
#       with:
#         subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#         resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
#         template: ./azuredeploy.json
#         parameters: storageAccountConnectionString=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
#
#     - name: Deploy Azure Function
#       uses: azure/functions-action@v1
#       with:
#         app-name: AzureResumeFunctionApp
#         package: ./AzureResumeFunction


name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
      - name: Deploy ARM Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: Azure_Resume  # Name of your resource group
          template: ./azuredeploy.json
          parameters: |
            functionAppName=AzureResumeFunctionApp
            cosmosDbAccountName=AzureResumeCosmosDB
          deploymentMode: Incremental

      # Deploy the Azure Function
      - name: Deploy Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: AzureResumeFunctionApp
          package: ./AzureResumeFunction
