name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r AzureResumeFunction/requirements.txt

    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template: ./azuredeploy.json
        parameters: storageAccountConnectionString=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}

    - name: Deploy Azure Function
      uses: azure/functions-action@v1
      with:
        app-name: AzureResumeFunctionApp
        package: ./AzureResumeFunction
